### ISSUE TITLE
ISSNs not found

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#26]
Hi casey, the below ISSNs for Elsevier titles are not found in journalsdb. Curious if they should be in there? This arose from some calculations Im doing for one of the consortia. 

0160-791x
0304-422x
1042-444x
1226-086x
1342-937x
1871-174x
2212-571x
2214-790x
2352-152x
2352-409x

**Comment by caseydm** [comment]
Hi @sckott. Want to let you know I've been crazy busy this week so will look at this tomorrow. Sorry for the delay.

**Comment by sckott** [comment]
no worries

**Comment by caseydm** [comment]
Hi Scott. Thankfully this is an easy one. The ISSNs are in the database but you have to capitalize the 'x' at the end. So 0160-791x should be 0160-791X. 

However, I made an update to the app so that ISSNs queries are automatically capitalized. So now the query is not case sensitive like before, and you can enter these ISSNs either way and they will work.

**Comment by sckott** [comment]
Awesome, thanks very much @caseydm ! 

Woopsy, I should have realized just by seeing lots of ISSN's that they should have been capitalized. Just looked at the data supplied to us in spreadsheets from one of our users, and the ISSNs did have lowercase 'x' in all those cases above. 

Thanks again.

**Comment by caseydm** [comment]
No problem at all!
