### ISSUE TITLE
Journals that change ISSN

### ISSUE THREAD

**Issue by sckott** [ourresearch/journalsdb#30]
In my work on looking for [journals that are not currently publishing](https://github.com/ourresearch/journalsdb/issues/27) I found this one which changed title and ISSN from 2019 to 2020, see https://www.tandfonline.com/action/journalInformation?journalCode=uahr21 

https://api.journalsdb.org/journals/1536-2426 (old)
vs
https://api.journalsdb.org/journals/2687-8003 (new)

Is there a way to crosswalk old to new ISSN with journalsdb in situations like these?

**Comment by caseydm** [comment]
Yes we have a command we can run for these instances, and we have been combining journals as they come up. I went ahead and combined these so that the old ISSNs are part of the new ISSN-L. We lose some DOI count stats when we do this initially, but I believe Richard's process maps them back once the ISSNs are merged together.

**Comment by sckott** [comment]
Thanks Casey. In the future, as I find these, just open an issue here?

**Comment by caseydm** [comment]
No problem! Yes, definitely.
